---
version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    groups:
      actions:
        patterns:
          - "actions/*"
      docker:
        patterns:
          - "docker/*"
    labels:
      - "bot"
    cooldown:
      default-days: 7
    commit-message:
      prefix: "[CHORE](deps)"
      include: "scope"
